### ISSUE TITLE
Named carets

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript#14]
Should we support the named carets for in-place var creation? [Use case](https://github.com/scala-subscript/eye-test/blob/master/src/main/scala/eyetest/app/Test.scala#L62):

``` scala
var firstResult = false
displayLetters(fontSize) ~~(result: Boolean)~~> let firstResult = result
```

Can be simplified to

``` scala
displayLetters(fontSize)^firstResult
```

**Comment by AndreVanDelft** [comment]
I was just thinking about such issues, when biking to/from the shops.
I think the dataflow arrow introduces already a named var or val; the scope is clear: the RHS.
 `displayLetters(fontSize)^firstResult` has no such clarity.

To indicate it is a `var` rather than a `val` you could write:

```
displayLetters(fontSize) ~~(var firstResult: Boolean)~~> ...
```

Such a style could even apply to plain Scala code (more precise: plain with a little extra syntax).

**Comment by anatoliykmetyuk** [comment]
Then I'd say it should be `f ~~(var x: Int)~~<`. The `~~>` makes you think it has an rhs, `~~<` points clearly where the data flows. Also, rhs should be absent, since the entire script will have the var in scope anyway.

Or, better yet,  `~~>(var x: Int)`.

**Comment by AndreVanDelft** [comment]
Misunderstanding? In our example the data flows from `displayLetters` to the right; that is my arrow direction.

**Comment by anatoliykmetyuk** [comment]
Yeah, but it makes you think something is ought to follow the `~~>`, just how it is with the ordinary dataflow.

**Comment by AndreVanDelft** [comment]
I misunderstood...
I meant to say that the normal dataflow arrow introduces a value in the RHS.
This does in-place var creation; I think more clearly than would be possible in other ways.
By adding "var" inside the arrow we have a variable on the RHS, rather than a value.
But in the use case we don't need that.

E.g.,

```
doTest(previousFont: Double) =
  let strategy = Strategy.batch()
  var fontSize = strategy.initialFont(previousFont)

  // Calibrating: get fontSize to the point where the user has hard times recognizing it
  displayLetters(fontSize) ~~(firstResult: Boolean)~~> 
  [
    if firstResult then let fontSize -= strategy.calibrationStep 
                   else let fontSize += strategy.calibrationStep
    displayLetters(fontSize) ~~(result: Boolean)~~> while(result == firstResult)
  ]

  // Testing
  [
    while(!strategy.isFinished) 
    displayLetters(fontSize) ~~(result: Boolean)~~> strategy.update(fontSize, result)
    let fontSize = strategy.nextFont
  ]
  ^strategy.success
```

**Comment by AndreVanDelft** [comment]
Alternatively (doTest renamed to calibrateAndTest):

```
calibrateAndTest(previousFont: Double) = calibrate: previousFont ~~(s:Strategy)~~> doTest: s

calibrate(previousFont: Double): Strategy =
  // get fontSize to the point where the user has hard times recognizing it
  let strategy = Strategy.batch()
  var fontSize = strategy.initialFont(previousFont)

  displayLetters(fontSize) ~~(firstResult: Boolean)~~> 
  [
    if firstResult then let fontSize -= strategy.calibrationStep 
                   else let fontSize += strategy.calibrationStep
    displayLetters(fontSize) ~~(result: Boolean)~~> while(result == firstResult)
  ]
  ^strategy

doTest(strategy: Strategy) =
  [
    while(!strategy.isFinished) 
    displayLetters(fontSize) ~~(result: Boolean)~~> strategy.update(fontSize, result)
    let fontSize = strategy.nextFont
  ]
  ^strategy.success
```
