### ISSUE TITLE
On exclusion, Dataflow proceeds to execute its `else` part

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript#19]
Here:

``` scala
live = a || {!!}
a = {..} ~~(x: Int)~~> println: x
```

`a` will get excluded after `{!!}` succeeds. But instead of deactivating ASAP, the dataflow proceeds to execute an `else` part in its `do-then-else` sequence, and throws an exception, because there's no handler for `null`.

`else` is not like `finally` in `try-catch-finally`, it is not supposed to be executed unconditionally. This behaviour can cause difficulties in large scripts: if a large script gets excluded, all the dataflows in the scripts called by it will be broken and will require `+~/~(null)~~> break` added to them.

**Comment by AndreVanDelft** [comment]
There are two kinds of deactivation: active and inactive; maybe these are not good names.
When a process gets excluded, it will become inactive, and its activation does not cause internally new activations. In this case, `a` is excluded, so no `else` part must be activated, even if it were present.
Suppose however the left hand side of the arrow is `[-]`, then the absence of an `else` arrow should also not lead to an error, since the binary arrow acts like a ternary one with the neutral process `[]` as RHS. In other words, these equivalences should hold:

```
do x then y  =  do x then y  else []
do x else y  =  do x then [] else y
```

I am not 100% sure about whether this goes Ok also for the related dataflow arrows; if you (Tolya or Andy) think there may be any problem with this then please comment.
