### ISSUE TITLE
Create result values for Swing scripts

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/subscript#21]
Current swing scripts have an output parameter, e.g.,

```
mouseMove(comp: Component, ?p : java.awt.Point) = ....
```

IMO we better replace these by result values:

```
mouseMove(comp: Component): java.awt.Point = ....
```

Then the callers should apply dataflow operators.

**Comment by AndreVanDelft** [comment]
I am not happy yet. `mouseMove` has now result value Any, instead of `java.awt.Point`, or better the `MouseMoved` event.

**Comment by anatoliykmetyuk** [comment]
So far, SubScript is untyped. We can of course make [ScriptResultHolder](https://github.com/scala-subscript/subscript/blob/master/framework/core/src/main/scala/subscript/vm/model/callgraph/CallGraph.scala#L34) covariant by removing [`var $`](https://github.com/scala-subscript/subscript/blob/master/framework/core/src/main/scala/subscript/vm/model/callgraph/CallGraph.scala#L35) (contravatiant position) and describing it through `private var _$: R`, `def $: R` and `def $_(v: Any) {_$ = v.asInstanceOf[R]}`. But this will still register type errors only on runtime - during assignment. So far, these errors are registered in pattern matches in the dataflows - not much difference.

Making SubScript typed implies teaching the compiler to typecheck scripts - to register the errors in compile time. This will require moving the parser and the typer-level preprocessing back to the compiler (perhaps via plugins) and doing major changes to the typecheck system to support SubScript.

So far, it's not a big issue that Swing events are untyped, since this is compensated by the dataflows, like [here](https://github.com/scala-subscript/examples/commit/453569c8400f314c319bba7a93cb38318ada104b#diff-2f767e483ed3fafc4912c24abe654cfaR120).

**Comment by AndreVanDelft** [comment]
So we can live with it for the time being.
The type checking would be easier in the forthcoming Dotty+ScalaParse based version of the SubScript compiler.

**Comment by anatoliykmetyuk** [comment]
Can we then close this issue? Since typecheck for SubScript is a wider issue then this one, it makes sense to make a separate one for it.

**Comment by AndreVanDelft** [comment]
Ok.
